<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 08 Nov 2025 00:09:37 +0100
 */
$conf['title'] = 'Netflix GC';
$conf['lang'] = 'es';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
