# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 08 Nov 2025 00:09:37 +0100
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

administrador:$2y$10$eMR64hLR4Edo7QxKwJUXee132jjv2jv3XVmNkbEch.8Cs4J9MgIH2:Administrador:joann.roah@ecci.edu.co:admin,user
